#!/bin/sh
# Compatibility shim for simplified test harnesses.
# Some upstream tests expect `mkdir .git/info` to succeed even if that
# directory already exists.

if test "$#" -eq 1 && test "$1" = ".git/info" && test -d ".git/info"
then
	exit 0
fi

exec /bin/mkdir "$@"
