#!/usr/bin/env python3
"""Refresh selected ported tests from git/t sources.

This keeps a reproducible process for importing upstream test scripts into
./tests while only carrying a small allowlisted subset at first.
"""

from __future__ import annotations

import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
UPSTREAM_DIR = ROOT / "git" / "t"
TESTS_DIR = ROOT / "tests"
HARNESS_DIR = TESTS_DIR / "harness"


def safe_git_to_gust(text: str) -> str:
    """Replace command token `git` with `gust` without touching `.git`/`GIT_*`."""

    return re.sub(r"(?<![A-Za-z0-9_./-])git(?![A-Za-z0-9_./-])", "gust", text)


def extract_test_blocks(script_text: str) -> dict[str, str]:
    """Extract simple `test_expect_success` blocks keyed by description."""

    pattern = re.compile(
        r"(^test_expect_success(?: [A-Z0-9_,]+)? '([^']+)' '\n.*?^'\n)",
        re.MULTILINE | re.DOTALL,
    )
    blocks: dict[str, str] = {}
    for full_block, description in pattern.findall(script_text):
        blocks[description] = full_block
    return blocks


def render_t0001(blocks: list[str]) -> str:
    """Render the generated `tests/t0001-init.sh` file."""

    body = "\n".join(blocks).rstrip() + "\n"
    return f"""#!/bin/sh
# Auto-generated by tests/harness/refresh_from_upstream.py
# Source: git/t/t0001-init.sh (allowlisted subset).

test_description='gust init'

cd "$(dirname "$0")" || exit 1
. ./test-lib.sh

check_config () {{
\tif test_path_is_dir "$1" &&
\t   test_path_is_file "$1/config" &&
\t   test_path_is_dir "$1/refs"
\tthen
\t\t: happy
\telse
\t\techo "expected a directory $1, a file $1/config and $1/refs"
\t\treturn 1
\tfi
}}

{body}
test_done
"""


def refresh_t0001() -> None:
    upstream = (UPSTREAM_DIR / "t0001-init.sh").read_text()
    allowlist = [
        line.strip()
        for line in (HARNESS_DIR / "t0001-init-allowlist.txt").read_text().splitlines()
        if line.strip() and not line.strip().startswith("#")
    ]

    available = extract_test_blocks(upstream)
    selected: list[str] = []
    missing: list[str] = []
    for description in allowlist:
        block = available.get(description)
        if block is None:
            missing.append(description)
            continue
        selected.append(safe_git_to_gust(block))

    if missing:
        joined = ", ".join(missing)
        raise SystemExit(f"Missing test blocks in upstream t0001-init.sh: {joined}")

    output = render_t0001(selected)
    (TESTS_DIR / "t0001-init.sh").write_text(output)


def main() -> None:
    selected_scripts = [
        line.strip()
        for line in (HARNESS_DIR / "selected-tests.txt").read_text().splitlines()
        if line.strip() and not line.strip().startswith("#")
    ]
    if selected_scripts != ["t0001-init.sh"]:
        raise SystemExit(
            "Only t0001-init.sh is wired right now; extend refresh script to add more."
        )
    refresh_t0001()
    print("Refreshed tests/t0001-init.sh from git/t/t0001-init.sh")


if __name__ == "__main__":
    main()
