#!/usr/bin/env python3
"""Emit Rust `synopsis_for_builtin` from vendored git/Documentation/*.adoc (t0450 parity).

Uses the same extraction rules as tests/t0450-txt-doc-vs-help.sh `adoc_to_synopsis`.
"""

from __future__ import annotations

import os
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
DOCS = Path(os.environ.get("GIT_DOCUMENTATION_DIR", str(REPO / "git" / "Documentation")))

# Must match `print_list_cmds` builtins union in grit/src/main.rs.
BUILTINS = [
    "add",
    "am",
    "archive",
    "bisect",
    "branch",
    "bundle",
    "checkout",
    "cherry-pick",
    "clean",
    "clone",
    "commit",
    "describe",
    "diff",
    "fetch",
    "format-patch",
    "gc",
    "grep",
    "init",
    "log",
    "merge",
    "mv",
    "notes",
    "pull",
    "push",
    "range-diff",
    "rebase",
    "reset",
    "restore",
    "revert",
    "rm",
    "shortlog",
    "show",
    "sparse-checkout",
    "stash",
    "status",
    "submodule",
    "switch",
    "tag",
    "worktree",
    "apply",
    "blame",
    "cherry",
    "config",
    "difftool",
    "fsck",
    "help",
    "mergetool",
    "prune",
    "reflog",
    "remote",
    "repack",
    "replace",
    "show-branch",
    "whatchanged",
    "cat-file",
    "check-attr",
    "check-ignore",
    "check-ref-format",
    "checkout-index",
    "commit-graph",
    "commit-tree",
    "count-objects",
    "diff-files",
    "diff-index",
    "diff-tree",
    "for-each-ref",
    "get-tar-commit-id",
    "hash-object",
    "index-pack",
    "ls-files",
    "ls-remote",
    "ls-tree",
    "merge-base",
    "merge-file",
    "mktag",
    "mktree",
    "multi-pack-index",
    "name-rev",
    "pack-objects",
    "pack-refs",
    "read-tree",
    "rev-list",
    "rev-parse",
    "show-ref",
    "symbolic-ref",
    "update-index",
    "update-ref",
    "verify-commit",
    "verify-pack",
    "verify-tag",
    "write-tree",
]

_QUOTED_GIT = re.compile(r"'(git[ a-z-]*)'")

# Merge-tree special case in t0450: strip " (deprecated)" from adoc synopsis for compare.
_DEPRECATED_SUFFIX = re.compile(r" \(deprecated\)$")


def adoc_to_synopsis(path: Path) -> str:
    """Mirror tests/t0450 adoc_to_synopsis sed script."""
    text = path.read_text(encoding="utf-8", errors="replace")
    lines = text.splitlines()
    in_block = False
    out: list[str] = []
    for line in lines:
        if not in_block:
            if line in ("[verse]", "[synopsis]"):
                in_block = True
            continue
        if line == "":
            break
        line = line.replace("{litdd}", "--")
        line = _QUOTED_GIT.sub(r"\1", line)
        out.append(line)
    return "\n".join(out)


def rust_raw_string(s: str) -> str:
    n = 1
    while n < 64:
        delim = "#" * n
        closer = '"' + delim
        if closer not in s:
            return f'r{delim}"{s}{closer}'
        n += 1
    raise RuntimeError("could not delimit raw string for synopsis")


def main() -> int:
    if not DOCS.is_dir():
        print(f"ERROR: documentation directory missing: {DOCS}", file=sys.stderr)
        return 1

    arms: list[str] = []
    for cmd in BUILTINS:
        adoc = DOCS / f"git-{cmd}.adoc"
        if not adoc.is_file():
            print(f"ERROR: missing {adoc}", file=sys.stderr)
            return 1
        syn = adoc_to_synopsis(adoc)
        if cmd == "merge-tree":
            syn = "\n".join(_DEPRECATED_SUFFIX.sub("", ln) for ln in syn.splitlines())
        if not syn.strip():
            print(f"ERROR: empty synopsis block in {adoc}", file=sys.stderr)
            return 1
        arms.append(f'        "{cmd}" => Some({rust_raw_string(syn)}),')

    print(
        "// @generated by scripts/generate-upstream-help-synopsis.py — do not edit.\n"
        "\n"
        "#[must_use]\n"
        "pub(super) fn synopsis_for_builtin(cmd: &str) -> Option<&'static str> {\n"
        "    match cmd {\n"
        + "\n".join(arms)
        + "\n        _ => None,\n"
        "    }\n"
        "}\n"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
